package jp.naver.android.npush.common;

public class NPushIntent {
    public static final String EXTRA_APPLICATION_CATEGORY_ID = "categoryid";
    public static final String EXTRA_APPLICATION_CLIENT_TYPE = "clientType";
    public static final String EXTRA_APPLICATION_KEEPALIVE = "keepalive";
    public static final String EXTRA_APPLICATION_PACKAGE_NAME = "packageName";
    public static final String EXTRA_APPLICATION_PENDING_INTENT = "app";
    public static final String EXTRA_APPLICATION_REQUESTCODE = "requestCode";
    public static final String EXTRA_APPLICATION_SERVICE_ID = "serviceid";
    public static final String EXTRA_COUNT = "count";
    public static final String EXTRA_EXCEPTION = "exception";
    public static final String EXTRA_STATE = "state";
    public static final String EXTRA_STATUS = "staus";
    public static final String EXTRA_TARGET_ID = "targetId";
    public static final String EXTRA_VERSION = "version";
    public static final String INFORM_STATUS_INTENT;
    public static final String NOTIFICATION_RECEIVE_INTENT;
    public static final String PARAM_CATEGORY_ID = "categoryId";
    public static final String PARAM_EVENT_ID = "eventId";
    public static final String PARAM_FROM = "from";
    public static final String PARAM_MESSAGE = "message";
    public static final String PARAM_SERVICE_ID = "serviceId";
    public static final String PROTOCOL_PARAMETER = "parameter";
    public static final String REQUEST_GETSTATE_INTENT;
    public static final String REQUEST_GETVERSION_INTENT;
    public static final String REQUEST_SUBSCRIBE_INTENT;
    public static final String REQUEST_UNSUBSCRIBE_INTENT;
    public static final String RESPONSE_GETSTATE_INTENT;
    public static final String RESPONSE_GETVERSION_INTENT;
    public static final String RESPONSE_SUBSCRIBE_INTENT;
    public static final String RESPONSE_UNSUBSCRIBE_INTENT;
    public static final int STAT_DEX_LOAD_FAILED = 5;
    public static final int STAT_NNI_CONNECTED = 0;
    public static final int STAT_NNI_DISCONNECTED = 1;
    public static final int STAT_UPGRADE_FAILED = 4;
    public static final int STAT_UPGRADE_FINISHED = 3;
    public static final int STAT_UPGRADE_STARTED = 2;
    public static final String Self = "nniclient_self";

    static {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("jp.naver.android.npush".toString());
        stringBuilder.append(".intent.action.SUBSCRIBE");
        REQUEST_SUBSCRIBE_INTENT = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("jp.naver.android.npush".toString());
        stringBuilder.append(".intent.action.UNSUBSCRIBE");
        REQUEST_UNSUBSCRIBE_INTENT = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("jp.naver.android.npush".toString());
        stringBuilder.append(".intent.action.GETSTATE");
        REQUEST_GETSTATE_INTENT = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("jp.naver.android.npush".toString());
        stringBuilder.append(".intent.action.GETVERSION");
        REQUEST_GETVERSION_INTENT = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("jp.naver.android.npush".toString());
        stringBuilder.append(".intent.action.SUBSCRIBE_RES");
        RESPONSE_SUBSCRIBE_INTENT = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("jp.naver.android.npush".toString());
        stringBuilder.append(".intent.action.UNSUBSCRIBE_RES");
        RESPONSE_UNSUBSCRIBE_INTENT = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("jp.naver.android.npush".toString());
        stringBuilder.append(".intent.action.CURRENTSTATE");
        RESPONSE_GETSTATE_INTENT = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("jp.naver.android.npush".toString());
        stringBuilder.append(".intent.action.CURRENTVERSION");
        RESPONSE_GETVERSION_INTENT = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("jp.naver.android.npush".toString());
        stringBuilder.append(".intent.action.RECEIVE");
        NOTIFICATION_RECEIVE_INTENT = stringBuilder.toString();
        stringBuilder = new StringBuilder();
        stringBuilder.append("jp.naver.android.npush".toString());
        stringBuilder.append(".intent.action.INFORM_STATUS");
        INFORM_STATUS_INTENT = stringBuilder.toString();
    }
}
