package com.applovin.impl.sdk;

import com.applovin.impl.a.q;
import com.google.android.exoplayer.DefaultLoadControl;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import org.apache.http.HttpStatus;
import org.apache.http.protocol.HTTP;

class ea {
    public static final ec<String> A = a("sc", "");
    public static final ec<String> B = a("ad_request_parameters", "");
    public static final ec<Boolean> C = a("ad_refresh_enabled", Boolean.TRUE);
    public static final ec<Long> D = a("ad_refresh_seconds", Long.valueOf(120));
    public static final ec<Boolean> E = a("mrec_ad_refresh_enabled", Boolean.TRUE);
    public static final ec<Long> F = a("mrec_ad_refresh_seconds", Long.valueOf(120));
    public static final ec<Boolean> G = a("leader_ad_refresh_enabled", Boolean.TRUE);
    public static final ec<Long> H = a("leader_ad_refresh_seconds", Long.valueOf(120));
    public static final ec<String> I = a("plugin_version", "");
    public static final ec<Boolean> J = a("ad_preload_enabled", Boolean.TRUE);
    public static final ec<Boolean> K = a("ad_resource_caching_enabled", Boolean.TRUE);
    public static final ec<Boolean> L = a("fail_ad_load_on_failed_video_cache", Boolean.TRUE);
    public static final ec<String> M = a("resource_cache_prefix", "https://vid.applovin.com/,https://pdn.applovin.com/,https://img.applovin.com/,https://d.applovin.com/,https://assets.applovin.com/,https://cdnjs.cloudflare.com/,http://vid.applovin.com/,http://pdn.applovin.com/,http://img.applovin.com/,http://d.applovin.com/,http://assets.applovin.com/,http://cdnjs.cloudflare.com/");
    public static final ec<String> N = a("ad_auto_preload_sizes", "");
    public static final ec<String> O = a("ad_auto_preload_msizes", "");
    public static final ec<Boolean> P = a("ad_auto_preload_incent", Boolean.TRUE);
    public static final ec<Boolean> Q = a("ad_auto_preload_mincent", Boolean.TRUE);
    public static final ec<Boolean> R = a("is_track_ad_info", Boolean.TRUE);
    public static final ec<Boolean> S = a("force_back_button_enabled_always", Boolean.FALSE);
    public static final ec<Integer> T = a("close_fade_in_time", Integer.valueOf(HttpStatus.SC_BAD_REQUEST));
    public static final ec<Boolean> U = a("show_close_on_exit", Boolean.TRUE);
    public static final ec<String> V = a("text_incent_prompt_title", "Earn a Reward");
    public static final ec<String> W = a("text_incent_prompt_body", "Would you like to watch a video for a reward?");
    public static final ec<String> X = a("text_incent_prompt_yes_option", "Watch Now");
    public static final ec<String> Y = a("text_incent_prompt_no_option", "No Thanks");
    public static final ec<String> Z = a("text_incent_completion_title", "Video Reward");
    public static final ec<Boolean> a = a("is_disabled", Boolean.FALSE);
    public static final ec<Integer> aA = a("preload_capacity_inter_videoa_indirect", Integer.valueOf(0));
    public static final ec<Integer> aB = a("extended_preload_capacity_banner_regular_direct", Integer.valueOf(15));
    public static final ec<Integer> aC = a("extended_preload_capacity_banner_regular_indirect", Integer.valueOf(15));
    public static final ec<Integer> aD = a("extended_preload_capacity_mrec_regular_direct", Integer.valueOf(15));
    public static final ec<Integer> aE = a("extended_preload_capacity_mrec_regular_indirect", Integer.valueOf(15));
    public static final ec<Integer> aF = a("extended_preload_capacity_leader_regular_direct", Integer.valueOf(15));
    public static final ec<Integer> aG = a("extended_preload_capacity_leader_regular_indirect", Integer.valueOf(15));
    public static final ec<Integer> aH = a("extended_preload_capacity_inter_regular_direct", Integer.valueOf(15));
    public static final ec<Integer> aI = a("extended_preload_capacity_inter_regular_indirect", Integer.valueOf(15));
    public static final ec<Integer> aJ = a("extended_preload_capacity_inter_videoa_direct", Integer.valueOf(15));
    public static final ec<Integer> aK = a("extended_preload_capacity_inter_videoa_indirect", Integer.valueOf(15));
    public static final ec<Integer> aL = a("preload_capacity_zone", Integer.valueOf(1));
    public static final ec<Integer> aM = a("preload_capacity_zone_native", Integer.valueOf(1));
    public static final ec<Integer> aN = a("extended_preload_capacity_zone", Integer.valueOf(15));
    public static final ec<Integer> aO = a("preload_capacity_native_native_direct", Integer.valueOf(0));
    public static final ec<Boolean> aP = a("dismiss_video_on_error", Boolean.TRUE);
    public static final ec<String> aQ = a("precache_delimiters", ")]',");
    public static final ec<Integer> aR = a("close_button_size_video", Integer.valueOf(30));
    public static final ec<Integer> aS = a("close_button_top_margin_video", Integer.valueOf(8));
    public static final ec<Integer> aT = a("close_button_right_margin_video", Integer.valueOf(4));
    public static final ec<Boolean> aU = a("force_back_button_enabled_poststitial", Boolean.FALSE);
    public static final ec<Boolean> aV = a("force_back_button_enabled_close_button", Boolean.FALSE);
    public static final ec<Integer> aW = a("close_button_touch_area", Integer.valueOf(0));
    public static final ec<Boolean> aX = a("is_video_skippable", Boolean.FALSE);
    public static final ec<Boolean> aY = a("cache_cleanup_enabled", Boolean.FALSE);
    public static final ec<Long> aZ = a("cache_file_ttl_seconds", Long.valueOf(86400));
    public static final ec<String> aa = a("text_incent_completion_body_success", "You have earned a reward!");
    public static final ec<String> ab = a("text_incent_completion_body_quota_exceeded", "You have already earned the maximum reward for today.");
    public static final ec<String> ac = a("text_incent_completion_body_reward_rejected", "Your reward was rejected.");
    public static final ec<String> ad = a("text_incent_completion_body_network_failure", "We were unable to contact the rewards server. Please try again later.");
    public static final ec<String> ae = a("text_incent_completion_close_option", "Okay");
    public static final ec<Boolean> af = a("incent_warning_enabled", Boolean.FALSE);
    public static final ec<String> ag = a("text_incent_warning_title", "Attention!");
    public static final ec<String> ah = a("text_incent_warning_body", "You won’t get your reward if the video hasn’t finished.");
    public static final ec<String> ai = a("text_incent_warning_close_option", HTTP.CONN_CLOSE);
    public static final ec<String> aj = a("text_incent_warning_continue_option", "Keep Watching");
    public static final ec<Boolean> ak = a("incent_nonvideo_warning_enabled", Boolean.FALSE);
    public static final ec<String> al = a("text_incent_nonvideo_warning_title", "Attention!");
    public static final ec<String> am = a("text_incent_nonvideo_warning_body", "You won’t get your reward if the game hasn’t finished.");
    public static final ec<String> an = a("text_incent_nonvideo_warning_close_option", HTTP.CONN_CLOSE);
    public static final ec<String> ao = a("text_incent_nonvideo_warning_continue_option", "Keep Playing");
    public static final ec<Boolean> ap = a("show_incent_prepopup", Boolean.TRUE);
    public static final ec<Boolean> aq = a("show_incent_postpopup", Boolean.TRUE);
    public static final ec<Integer> ar = a("preload_capacity_banner_regular_direct", Integer.valueOf(0));
    public static final ec<Integer> as = a("preload_capacity_banner_regular_indirect", Integer.valueOf(0));
    public static final ec<Integer> at = a("preload_capacity_mrec_regular_direct", Integer.valueOf(0));
    public static final ec<Integer> au = a("preload_capacity_mrec_regular_indirect", Integer.valueOf(0));
    public static final ec<Integer> av = a("preload_capacity_leader_regular_direct", Integer.valueOf(0));
    public static final ec<Integer> aw = a("preload_capacity_leader_regular_indirect", Integer.valueOf(0));
    public static final ec<Integer> ax = a("preload_capacity_inter_regular_direct", Integer.valueOf(0));
    public static final ec<Integer> ay = a("preload_capacity_inter_regular_indirect", Integer.valueOf(0));
    public static final ec<Integer> az = a("preload_capacity_inter_videoa_direct", Integer.valueOf(0));
    public static final ec<Boolean> b = a("honor_publisher_settings", Boolean.TRUE);
    public static final ec<Boolean> bA = a("android_gc_on_widget_detach", Boolean.TRUE);
    public static final ec<Boolean> bB = a("lhs_close_button_video", Boolean.FALSE);
    public static final ec<Boolean> bC = a("lhs_skip_button", Boolean.TRUE);
    public static final ec<Boolean> bD = a("countdown_toggleable", Boolean.FALSE);
    public static final ec<Integer> bE = a("native_batch_precache_count", Integer.valueOf(1));
    public static final ec<Boolean> bF = a("mute_controls_enabled", Boolean.FALSE);
    public static final ec<Boolean> bG = a("allow_user_muting", Boolean.TRUE);
    public static final ec<Integer> bH = a("mute_button_size", Integer.valueOf(32));
    public static final ec<Integer> bI = a("mute_button_margin", Integer.valueOf(10));
    public static final ec<Integer> bJ = a("mute_button_gravity", Integer.valueOf(85));
    public static final ec<Boolean> bK = a("qq", Boolean.FALSE);
    public static final ec<Boolean> bL = a("qq1", Boolean.TRUE);
    public static final ec<Boolean> bM = a("hw_accelerate_webviews", Boolean.FALSE);
    public static final ec<Boolean> bN = a("mute_videos", Boolean.FALSE);
    public static final ec<Boolean> bO = a("show_mute_by_default", Boolean.FALSE);
    public static final ec<Boolean> bP = a("mute_with_user_settings", Boolean.TRUE);
    public static final ec<String> bQ = a("top_level_events", "landing,paused,resumed,checkout,iap");
    public static final ec<Boolean> bR = a("events_enabled", Boolean.TRUE);
    public static final ec<Boolean> bS = a("force_ssl", Boolean.FALSE);
    public static final ec<Integer> bT = a("postback_service_max_queue_size", Integer.valueOf(100));
    public static final ec<Integer> bU = a("max_postback_attempts", Integer.valueOf(3));
    public static final ec<Boolean> bV = a("click_overlay_enabled", Boolean.FALSE);
    public static final ec<String> bW = a("click_overlay_color", "#66000000");
    public static final ec<Integer> bX = a("click_tracking_retry_count_v1", Integer.valueOf(3));
    public static final ec<Integer> bY = a("click_tracking_retry_delay", Integer.valueOf(2000));
    public static final ec<Integer> bZ = a("click_tracking_timeout", Integer.valueOf(10000));
    public static final ec<Integer> ba = a("cache_max_size_mb", Integer.valueOf(-1));
    public static final ec<Boolean> bb = a("preload_merge_init_tasks_inter_regular_direct", Boolean.FALSE);
    public static final ec<Boolean> bc = a("preload_merge_init_tasks_inter_videoa_direct", Boolean.FALSE);
    public static final ec<Boolean> bd = a("preload_merge_init_tasks_banner_regular_direct", Boolean.FALSE);
    public static final ec<Boolean> be = a("preload_merge_init_tasks_mrec_regular_direct", Boolean.FALSE);
    public static final ec<Boolean> bf = a("preload_merge_init_tasks_leader_regular_direct", Boolean.FALSE);
    public static final ec<Boolean> bg = a("preload_merge_init_tasks_inter_regular_indirect", Boolean.FALSE);
    public static final ec<Boolean> bh = a("preload_merge_init_tasks_inter_videoa_indirect", Boolean.FALSE);
    public static final ec<Boolean> bi = a("preload_merge_init_tasks_banner_regular_indirect", Boolean.FALSE);
    public static final ec<Boolean> bj = a("preload_merge_init_tasks_mrec_regular_indirect", Boolean.FALSE);
    public static final ec<Boolean> bk = a("preload_merge_init_tasks_leader_regular_indirect", Boolean.FALSE);
    public static final ec<Boolean> bl = a("preload_merge_init_tasks_zones", Boolean.FALSE);
    public static final ec<Integer> bm = a("submit_postback_timeout", Integer.valueOf(10000));
    public static final ec<Integer> bn = a("submit_postback_retries", Integer.valueOf(4));
    public static final ec<Integer> bo = a("widget_imp_tracking_delay", Integer.valueOf(2000));
    public static final ec<Boolean> bp = a("draw_countdown_clock", Boolean.TRUE);
    public static final ec<Integer> bq = a("countdown_clock_size", Integer.valueOf(32));
    public static final ec<Integer> br = a("countdown_clock_stroke_size", Integer.valueOf(4));
    public static final ec<Integer> bs = a("countdown_clock_text_size", Integer.valueOf(28));
    public static final ec<Boolean> bt = a("ad_auto_preload_native", Boolean.FALSE);
    public static final ec<Boolean> bu = a("preload_native_ad_on_dequeue", Boolean.FALSE);
    public static final ec<Boolean> bv = a("widget_fail_on_slot_count_diff", Boolean.TRUE);
    public static final ec<Boolean> bw = a("video_zero_length_as_computed", Boolean.FALSE);
    public static final ec<Integer> bx = a("video_countdown_clock_margin", Integer.valueOf(10));
    public static final ec<Integer> by = a("video_countdown_clock_gravity", Integer.valueOf(83));
    public static final ec<Integer> bz = a("widget_latch_timeout_ms", Integer.valueOf(500));
    public static final ec<Boolean> c = a("honor_publisher_settings_verbose_logging", Boolean.TRUE);
    public static final ec<Boolean> cA = a("handle_window_actions", Boolean.FALSE);
    public static final ec<String> cB = a("soft_buttons_resource_id", "config_showNavigationBar");
    public static final ec<Boolean> cC = a("immediate_render", Boolean.FALSE);
    public static final ec<Long> cD = a("video_resume_delay", Long.valueOf(250));
    public static final ec<Long> cE = a("force_hide_status_bar_delay_ms", Long.valueOf(0));
    public static final ec<Boolean> cF = a("load_ads_if_no_internet", Boolean.TRUE);
    public static final ec<Boolean> cG = a("display_ads_if_no_internet", Boolean.TRUE);
    public static final ec<Boolean> cH = a("network_available_if_none_detected", Boolean.TRUE);
    public static final ec<Long> cI = a("expandable_close_button_animation_duration_ms", Long.valueOf(300));
    public static final ec<Integer> cJ = a("expandable_close_button_size", Integer.valueOf(27));
    public static final ec<Integer> cK = a("expandable_h_close_button_margin", Integer.valueOf(10));
    public static final ec<Integer> cL = a("expandable_t_close_button_margin", Integer.valueOf(10));
    public static final ec<Boolean> cM = a("expandable_lhs_close_button", Boolean.FALSE);
    public static final ec<Integer> cN = a("expandable_close_button_touch_area", Integer.valueOf(0));
    public static final ec<Long> cO = a("progress_bar_step", Long.valueOf(25));
    public static final ec<Integer> cP = a("progress_bar_scale", Integer.valueOf(10000));
    public static final ec<Integer> cQ = a("progress_bar_vertical_padding", Integer.valueOf(-8));
    public static final ec<Boolean> cR = a("click_failed_expand", Boolean.FALSE);
    public static final ec<Boolean> cS = a("ignore_is_showing", Boolean.FALSE);
    public static final ec<Boolean> cT = a("wrapped_zones", Boolean.FALSE);
    public static final ec<String> cU = a("wrapped_sizes", "");
    public static final ec<Boolean> cV = a("return_wrapped_ad_on_empty_queue", Boolean.FALSE);
    public static final ec<Boolean> cW = a("consider_wrapped_ad_preloaded", Boolean.FALSE);
    public static final ec<Boolean> cX = a("preload_persisted_zones", Boolean.TRUE);
    public static final ec<Boolean> cY = a("persist_zones", Boolean.TRUE);
    public static final ec<Boolean> cZ = a("validate_zone_input", Boolean.FALSE);
    public static final ec<Integer> ca = a("android_click_spinner_size", Integer.valueOf(50));
    public static final ec<Integer> cb = a("android_click_spinner_style", Integer.valueOf(16973853));
    public static final ec<Boolean> cc = a("android_require_external_storage_permission", Boolean.TRUE);
    public static final ec<Boolean> cd = a("android_drop_nomedia", Boolean.TRUE);
    public static final ec<Boolean> ce = a("native_auto_cache_preload_resources", Boolean.TRUE);
    public static final ec<Boolean> cf = a("video_immersive_mode_enabled", Boolean.FALSE);
    public static final ec<String> cg = a("fireos_manufacturer_list", "amazon");
    public static final ec<Boolean> ch = a("fireos_collect_google_idfa_on_fail", Boolean.FALSE);
    public static final ec<Boolean> ci = a("fireos_hide_adview_on_init", Boolean.TRUE);
    public static final ec<Boolean> cj = a("fireos_load_empty_adview_on_init", Boolean.FALSE);
    public static final ec<Boolean> ck = a("sanitize_webview", Boolean.FALSE);
    public static final ec<Boolean> cl = a("force_rerender", Boolean.FALSE);
    public static final ec<String> cm = a("webview_package_name", "com.google.android.webview");
    public static final ec<Boolean> cn = a("check_webview_has_gesture", Boolean.FALSE);
    public static final ec<Boolean> co = a("adr", Boolean.FALSE);
    public static final ec<Boolean> cp = a("hgn", Boolean.FALSE);
    public static final ec<String> cq = a("emulator_hardware_list", "ranchu,goldfish,vbox");
    public static final ec<String> cr = a("emulator_device_list", "generic,vbox");
    public static final ec<String> cs = a("emulator_manufacturer_list", "Genymotion");
    public static final ec<String> ct = a("emulator_model_list", "Android SDK built for x86");
    public static final ec<Long> cu = a("inter_display_delay", Long.valueOf(200));
    public static final ec<Float> cv = a("volume_normalization_factor", Float.valueOf(6.6666665f));
    public static final ec<Boolean> cw = a("lock_specific_orientation", Boolean.FALSE);
    public static final ec<Boolean> cx = a("video_callbacks_for_incent_nonvideo_ads_enabled", Boolean.TRUE);
    public static final ec<Boolean> cy = a("user_agent_collection_enabled", Boolean.FALSE);
    public static final ec<Long> cz = a("user_agent_collection_timeout_ms", Long.valueOf(600));
    public static final ec<Boolean> d = a("honor_publisher_settings_auto_preload_ad_sizes", Boolean.TRUE);
    public static final ec<Boolean> dA = a("vast_validate_with_extension_if_no_video_type", Boolean.TRUE);
    public static final ec<Integer> dB = a("num_ads_preload_ahead", Integer.valueOf(2));
    public static final ec<Boolean> dC = a("mediation_load_last_session_adapters_on_next_init", Boolean.TRUE);
    public static final ec<Boolean> dD = a("mediation_load_predefined_adapters_on_next_init", Boolean.TRUE);
    public static final ec<Boolean> dE = a("mediation_track_imp", Boolean.TRUE);
    public static final ec<Boolean> dF = a("mediation_track_clk", Boolean.TRUE);
    public static final ec<Boolean> dG = a("mediation_track_err", Boolean.TRUE);
    public static final ec<Boolean> dH = a("submit_ad_stats_enabled", Boolean.FALSE);
    public static final ec<Integer> dI = a("submit_ad_stats_connection_timeout", Integer.valueOf(DefaultLoadControl.DEFAULT_HIGH_WATERMARK_MS));
    public static final ec<Integer> dJ = a("submit_ad_stats_retry_count", Integer.valueOf(1));
    public static final ec<Integer> dK = a("submit_ad_stats_max_count", Integer.valueOf(500));
    private static final List<?> dL = Arrays.asList(new Class[]{Boolean.class, Float.class, Integer.class, Long.class, String.class});
    private static final List<ec<?>> dM = new ArrayList();
    public static final ec<Boolean> da = a("cleanup_webview", Boolean.FALSE);
    public static final ec<Boolean> db = a("dismiss_expanded_adview_on_refresh", Boolean.FALSE);
    public static final ec<Boolean> dc = a("dismiss_expanded_adview_on_detach", Boolean.FALSE);
    public static final ec<Boolean> dd = a("detach_update_listener_on_pause", Boolean.FALSE);
    public static final ec<Boolean> de = a("contract_on_close_ad_command", Boolean.FALSE);
    public static final ec<Integer> df = a("response_buffer_size", Integer.valueOf(16000));
    public static final ec<Boolean> dg = a("sp_apply", Boolean.TRUE);
    public static final ec<Boolean> dh = a("sr_0", Boolean.TRUE);
    public static final ec<Integer> di = a("fetch_basic_settings_connection_timeout_ms", Integer.valueOf(5000));
    public static final ec<Integer> dj = a("fetch_basic_settings_retry_count", Integer.valueOf(3));
    public static final ec<Integer> dk = a("fetch_basic_settings_retry_delay_ms", Integer.valueOf(2000));
    public static final ec<Boolean> dl = a("session_tracking_enabled", Boolean.FALSE);
    public static final ec<Boolean> dm = a("session_tracking_cooldown_on_event_fire", Boolean.TRUE);
    public static final ec<Long> dn = a("session_tracking_resumed_cooldown_minutes", Long.valueOf(90));
    public static final ec<Long> do = a("session_tracking_paused_cooldown_minutes", Long.valueOf(90));
    public static final ec<Boolean> dp = a("track_app_paused", Boolean.FALSE);
    public static final ec<Integer> dq = a("vast_max_wrapper_depth", Integer.valueOf(5));
    public static final ec<Integer> dr = a("vast_wrapper_resolution_retry_count_v1", Integer.valueOf(1));
    public static final ec<Integer> ds = a("vast_wrapper_resolution_connection_timeout", Integer.valueOf(DefaultLoadControl.DEFAULT_HIGH_WATERMARK_MS));
    public static final ec<Integer> dt = a("vast_max_response_length", Integer.valueOf(640000));
    public static final ec<Integer> du = a("vast_video_selection_policy", Integer.valueOf(q.MEDIUM.ordinal()));
    public static final ec<String> dv = a("vast_image_html", "<html><head><style>html,body{height:100%;width:100%}body{background-image:url({SOURCE});background-repeat:no-repeat;background-size:contain;background-position:center;}a{position:absolute;top:0;bottom:0;left:0;right:0}</style></head><body><a href=\"applovin://com.applovin.sdk/adservice/track_click_now\"></a></body></html>");
    public static final ec<String> dw = a("vast_link_html", "<html><head><style>html,body,iframe{height:100%;width:100%;}body{margin:0}iframe{border:0;overflow:hidden;position:absolute}</style></head><body><iframe src={SOURCE} frameborder=0></iframe></body></html>");
    public static final ec<Long> dx = a("vast_progress_tracking_countdown_step", Long.valueOf(1000));
    public static final ec<String> dy = a("vast_unsupported_video_types", "video/ogg,video/x-flv");
    public static final ec<String> dz = a("vast_unsupported_video_extensions", "ogv,flv");
    public static final ec<Boolean> e = a("honor_publisher_settings_auto_preload_ad_types", Boolean.TRUE);
    public static final ec<String> f = a("device_id", "");
    public static final ec<String> g = a("publisher_id", "");
    public static final ec<String> h = a("device_token", "");
    public static final ec<Integer> i = a("submit_data_retry_count_v1", Integer.valueOf(1));
    public static final ec<Integer> j = a("vr_retry_count_v1", Integer.valueOf(1));
    public static final ec<Integer> k = a("fetch_ad_retry_count_v1", Integer.valueOf(1));
    public static final ec<Boolean> l = a("is_verbose_logging", Boolean.FALSE);
    public static final ec<String> m = a("api_endpoint", "https://d.applovin.com/");
    public static final ec<String> n = a("adserver_endpoint", "https://a.applovin.com/");
    public static final ec<String> o = a("mediation_tracking_endpoint", "https://rt.applovin.com/med");
    public static final ec<String> p = a("event_tracking_endpoint", "https://rt.applovin.com/pix");
    public static final ec<String> q = a("api_backup_endpoint", "https://d.applvn.com/");
    public static final ec<String> r = a("adserver_backup_endpoint", "https://a.applvn.com/");
    public static final ec<String> s = a("event_tracking_backup_endpoint", "https://rt.applvn.com/pix");
    public static final ec<Long> t = a("get_retry_delay_v1", Long.valueOf(10000));
    public static final ec<String> u = a("hash_algorithm", "SHA-1");
    public static final ec<Integer> v = a("short_hash_size", Integer.valueOf(16));
    public static final ec<Integer> w = a("http_connection_timeout", Integer.valueOf(DefaultLoadControl.DEFAULT_HIGH_WATERMARK_MS));
    public static final ec<Integer> x = a("fetch_ad_connection_timeout", Integer.valueOf(DefaultLoadControl.DEFAULT_HIGH_WATERMARK_MS));
    public static final ec<Integer> y = a("http_socket_timeout", Integer.valueOf(20000));
    public static final ec<Integer> z = a("ad_session_minutes", Integer.valueOf(60));

    private static <T> ec<T> a(String str, T t) {
        if (t == null) {
            throw new IllegalArgumentException("No default value specified");
        } else if (dL.contains(t.getClass())) {
            ec<T> ecVar = new ec(str, t, null);
            dM.add(ecVar);
            return ecVar;
        } else {
            StringBuilder stringBuilder = new StringBuilder("Unsupported value type: ");
            stringBuilder.append(t.getClass());
            throw new IllegalArgumentException(stringBuilder.toString());
        }
    }

    public static Collection<ec<?>> a() {
        return Collections.unmodifiableList(dM);
    }

    public static int b() {
        return dM.size();
    }
}
