package androidx.constraintlayout.widget;

import android.os.Build.VERSION;
import androidx.constraintlayout.widget.Constraints.LayoutParams;
import com.google.android.gms.maps.model.BitmapDescriptorFactory;
import java.util.Arrays;

final class c {
    public int A;
    public int B;
    public int C;
    public int D;
    public int E;
    public int F;
    public int G;
    public int H;
    public int I;
    public int J;
    public int K;
    public int L;
    public int M;
    public int N;
    public int O;
    public int P;
    public float Q;
    public float R;
    public int S;
    public int T;
    public float U;
    public boolean V;
    public float W;
    public float X;
    public float Y;
    public float Z;
    boolean a;
    public float aa;
    public float ab;
    public float ac;
    public float ad;
    public float ae;
    public float af;
    public float ag;
    public boolean ah;
    public boolean ai;
    public int aj;
    public int ak;
    public int al;
    public int am;
    public int an;
    public int ao;
    public float ap;
    public float aq;
    public boolean ar;
    public int as;
    public int at;
    public int[] au;
    public String av;
    public int b;
    public int c;
    int d;
    public int e;
    public int f;
    public float g;
    public int h;
    public int i;
    public int j;
    public int k;
    public int l;
    public int m;
    public int n;
    public int o;
    public int p;
    public int q;
    public int r;
    public int s;
    public int t;
    public float u;
    public float v;
    public String w;
    public int x;
    public int y;
    public float z;

    private c() {
        this.a = false;
        this.e = -1;
        this.f = -1;
        this.g = -1.0f;
        this.h = -1;
        this.i = -1;
        this.j = -1;
        this.k = -1;
        this.l = -1;
        this.m = -1;
        this.n = -1;
        this.o = -1;
        this.p = -1;
        this.q = -1;
        this.r = -1;
        this.s = -1;
        this.t = -1;
        this.u = 0.5f;
        this.v = 0.5f;
        this.w = null;
        this.x = -1;
        this.y = 0;
        this.z = BitmapDescriptorFactory.HUE_RED;
        this.A = -1;
        this.B = -1;
        this.C = -1;
        this.D = -1;
        this.E = -1;
        this.F = -1;
        this.G = -1;
        this.H = -1;
        this.I = -1;
        this.J = 0;
        this.K = -1;
        this.L = -1;
        this.M = -1;
        this.N = -1;
        this.O = -1;
        this.P = -1;
        this.Q = BitmapDescriptorFactory.HUE_RED;
        this.R = BitmapDescriptorFactory.HUE_RED;
        this.S = 0;
        this.T = 0;
        this.U = 1.0f;
        this.V = false;
        this.W = BitmapDescriptorFactory.HUE_RED;
        this.X = BitmapDescriptorFactory.HUE_RED;
        this.Y = BitmapDescriptorFactory.HUE_RED;
        this.Z = BitmapDescriptorFactory.HUE_RED;
        this.aa = 1.0f;
        this.ab = 1.0f;
        this.ac = Float.NaN;
        this.ad = Float.NaN;
        this.ae = BitmapDescriptorFactory.HUE_RED;
        this.af = BitmapDescriptorFactory.HUE_RED;
        this.ag = BitmapDescriptorFactory.HUE_RED;
        this.ah = false;
        this.ai = false;
        this.aj = 0;
        this.ak = 0;
        this.al = -1;
        this.am = -1;
        this.an = -1;
        this.ao = -1;
        this.ap = 1.0f;
        this.aq = 1.0f;
        this.ar = false;
        this.as = -1;
        this.at = -1;
    }

    /* synthetic */ c(byte b) {
        this();
    }

    private void a(int i, LayoutParams layoutParams) {
        a(i, (ConstraintLayout.LayoutParams) layoutParams);
        this.U = layoutParams.an;
        this.X = layoutParams.aq;
        this.Y = layoutParams.ar;
        this.Z = layoutParams.as;
        this.aa = layoutParams.at;
        this.ab = layoutParams.au;
        this.ac = layoutParams.av;
        this.ad = layoutParams.aw;
        this.ae = layoutParams.ax;
        this.af = layoutParams.ay;
        this.ag = layoutParams.az;
        this.W = layoutParams.ap;
        this.V = layoutParams.ao;
    }

    private void a(int i, ConstraintLayout.LayoutParams layoutParams) {
        this.d = i;
        this.h = layoutParams.d;
        this.i = layoutParams.e;
        this.j = layoutParams.f;
        this.k = layoutParams.g;
        this.l = layoutParams.h;
        this.m = layoutParams.i;
        this.n = layoutParams.j;
        this.o = layoutParams.k;
        this.p = layoutParams.l;
        this.q = layoutParams.p;
        this.r = layoutParams.q;
        this.s = layoutParams.r;
        this.t = layoutParams.s;
        this.u = layoutParams.z;
        this.v = layoutParams.A;
        this.w = layoutParams.B;
        this.x = layoutParams.m;
        this.y = layoutParams.n;
        this.z = layoutParams.o;
        this.A = layoutParams.Q;
        this.B = layoutParams.R;
        this.C = layoutParams.S;
        this.g = layoutParams.c;
        this.e = layoutParams.a;
        this.f = layoutParams.b;
        this.b = layoutParams.width;
        this.c = layoutParams.height;
        this.D = layoutParams.leftMargin;
        this.E = layoutParams.rightMargin;
        this.F = layoutParams.topMargin;
        this.G = layoutParams.bottomMargin;
        this.Q = layoutParams.F;
        this.R = layoutParams.E;
        this.T = layoutParams.H;
        this.S = layoutParams.G;
        this.ah = layoutParams.T;
        this.ai = layoutParams.U;
        this.aj = layoutParams.I;
        this.ak = layoutParams.J;
        this.ah = layoutParams.T;
        this.al = layoutParams.M;
        this.am = layoutParams.N;
        this.an = layoutParams.K;
        this.ao = layoutParams.L;
        this.ap = layoutParams.O;
        this.aq = layoutParams.P;
        if (VERSION.SDK_INT >= 17) {
            this.H = layoutParams.getMarginEnd();
            this.I = layoutParams.getMarginStart();
        }
    }

    public final void a(ConstraintLayout.LayoutParams layoutParams) {
        layoutParams.d = this.h;
        layoutParams.e = this.i;
        layoutParams.f = this.j;
        layoutParams.g = this.k;
        layoutParams.h = this.l;
        layoutParams.i = this.m;
        layoutParams.j = this.n;
        layoutParams.k = this.o;
        layoutParams.l = this.p;
        layoutParams.p = this.q;
        layoutParams.q = this.r;
        layoutParams.r = this.s;
        layoutParams.s = this.t;
        layoutParams.leftMargin = this.D;
        layoutParams.rightMargin = this.E;
        layoutParams.topMargin = this.F;
        layoutParams.bottomMargin = this.G;
        layoutParams.x = this.P;
        layoutParams.y = this.O;
        layoutParams.z = this.u;
        layoutParams.A = this.v;
        layoutParams.m = this.x;
        layoutParams.n = this.y;
        layoutParams.o = this.z;
        layoutParams.B = this.w;
        layoutParams.Q = this.A;
        layoutParams.R = this.B;
        layoutParams.F = this.Q;
        layoutParams.E = this.R;
        layoutParams.H = this.T;
        layoutParams.G = this.S;
        layoutParams.T = this.ah;
        layoutParams.U = this.ai;
        layoutParams.I = this.aj;
        layoutParams.J = this.ak;
        layoutParams.M = this.al;
        layoutParams.N = this.am;
        layoutParams.K = this.an;
        layoutParams.L = this.ao;
        layoutParams.O = this.ap;
        layoutParams.P = this.aq;
        layoutParams.S = this.C;
        layoutParams.c = this.g;
        layoutParams.a = this.e;
        layoutParams.b = this.f;
        layoutParams.width = this.b;
        layoutParams.height = this.c;
        if (VERSION.SDK_INT >= 17) {
            layoutParams.setMarginStart(this.I);
            layoutParams.setMarginEnd(this.H);
        }
        layoutParams.a();
    }

    public final /* synthetic */ Object clone() throws CloneNotSupportedException {
        c cVar = new c();
        cVar.a = this.a;
        cVar.b = this.b;
        cVar.c = this.c;
        cVar.e = this.e;
        cVar.f = this.f;
        cVar.g = this.g;
        cVar.h = this.h;
        cVar.i = this.i;
        cVar.j = this.j;
        cVar.k = this.k;
        cVar.l = this.l;
        cVar.m = this.m;
        cVar.n = this.n;
        cVar.o = this.o;
        cVar.p = this.p;
        cVar.q = this.q;
        cVar.r = this.r;
        cVar.s = this.s;
        cVar.t = this.t;
        cVar.u = this.u;
        cVar.v = this.v;
        cVar.w = this.w;
        cVar.A = this.A;
        cVar.B = this.B;
        cVar.u = this.u;
        cVar.u = this.u;
        cVar.u = this.u;
        cVar.u = this.u;
        cVar.u = this.u;
        cVar.C = this.C;
        cVar.D = this.D;
        cVar.E = this.E;
        cVar.F = this.F;
        cVar.G = this.G;
        cVar.H = this.H;
        cVar.I = this.I;
        cVar.J = this.J;
        cVar.K = this.K;
        cVar.L = this.L;
        cVar.M = this.M;
        cVar.N = this.N;
        cVar.O = this.O;
        cVar.P = this.P;
        cVar.Q = this.Q;
        cVar.R = this.R;
        cVar.S = this.S;
        cVar.T = this.T;
        cVar.U = this.U;
        cVar.V = this.V;
        cVar.W = this.W;
        cVar.X = this.X;
        cVar.Y = this.Y;
        cVar.Z = this.Z;
        cVar.aa = this.aa;
        cVar.ab = this.ab;
        cVar.ac = this.ac;
        cVar.ad = this.ad;
        cVar.ae = this.ae;
        cVar.af = this.af;
        cVar.ag = this.ag;
        cVar.ah = this.ah;
        cVar.ai = this.ai;
        cVar.aj = this.aj;
        cVar.ak = this.ak;
        cVar.al = this.al;
        cVar.am = this.am;
        cVar.an = this.an;
        cVar.ao = this.ao;
        cVar.ap = this.ap;
        cVar.aq = this.aq;
        cVar.as = this.as;
        cVar.at = this.at;
        if (this.au != null) {
            cVar.au = Arrays.copyOf(this.au, this.au.length);
        }
        cVar.x = this.x;
        cVar.y = this.y;
        cVar.z = this.z;
        cVar.ar = this.ar;
        return cVar;
    }

    static /* synthetic */ void a(c cVar, ConstraintHelper constraintHelper, int i, LayoutParams layoutParams) {
        cVar.a(i, layoutParams);
        if (constraintHelper instanceof Barrier) {
            cVar.at = 1;
            Barrier barrier = (Barrier) constraintHelper;
            cVar.as = barrier.a();
            cVar.au = barrier.c();
        }
    }
}
